[package]
name = "dtu-decompile"
version.workspace = true
edition.workspace = true

[[bin]]
name = "dtu-decompile"
path = "src/main.rs"

[dependencies]
dtu = { path = "../dtu", default-features = false, features = [] }
log = { version = "0.4", features = ["std"] }
clap = { workspace = true }
anyhow = { workspace = true }
