from pathlib import Path
from typing import ClassVar, Optional, Mapping, Sequence, Callable


def split_smali_args(args: str) -> list[str]:
    """
    Take a combined smali signature and split it into individual arguments
    """


class Context:
    def __new__(cls) -> Context: ...

    def get_target_api_level(self) -> int: ...

    def maybe_get_env(self, key: str) -> Optional[str]: ...
    def maybe_get_bin(self, bin: str) -> Optional[str]: ...

    def has_bin(self, bin: str) -> bool: ...
    def get_bin(self, bin: str) -> str: ...
    def unchecked_get_bin(self, bin: str) -> str: ...

    def has_env(self, key: str) -> bool: ...
    def get_env(self, key: str) -> str: ...
    def unchecked_get_env(self, key: str) -> str: ...

    def get_project_dir(self) -> Path: ...
    def get_project_config_file(self) -> Path: ...
    def get_test_app_dir(self) -> Path: ...
    def get_project_dir_child(self, child: str) -> Path: ...

    def get_output_dir(self) -> Path: ...
    def get_output_dir_child(self, child: str) -> Path: ...

    def get_project_cache_dir(self) -> Path: ...
    def get_cache_dir(self) -> Path: ...

    def get_smalisa_analysis_dir(self) -> Path: ...
    def get_graph_import_dir(self) -> Path: ...
    def get_selinux_dir(self) -> Path: ...
    def get_sqlite_dir(self) -> Path: ...

    def get_frameworks_dir(self) -> Path: ...
    def get_apks_dir(self) -> Path: ...
    def get_smali_dir(self) -> Path: ...

    def get_user_local_dir(self) -> Path: ...
    def get_user_config_dir(self) -> Path: ...


class FileStore:
    def __new__(cls, ctx: Optional[Context] = ...) -> FileStore: ...

    def put_file(self, local_path: str, remote_path: str) -> None: ...
    def get_file(self, remote_path: str, local_path: str) -> None: ...

    def list_files(self, dir: Optional[str] = ...) -> list[str]: ...

    def remove_file(self, file: str) -> None: ...

    def name(self) -> str: ...


class FindType:
    Any: FindType
    File: FindType
    Dir: FindType


class FindLimits:
    mindepth: Optional[int]
    maxdepth: Optional[int]

    def __new__(
        cls, mindepth: Optional[int] = ..., maxdepth: Optional[int] = ...
    ) -> FindLimits: ...


class FindName:
    @staticmethod
    def Suffix(arg: str) -> FindName: ...
    @staticmethod
    def Prefix(arg: str) -> FindName: ...
    @staticmethod
    def Exact(arg: str) -> FindName: ...
    @staticmethod
    def CaseInsensitive(arg: str) -> FindName: ...


class DeviceFS:
    def __new__(cls, ctx: Optional[Context] = ...) -> DeviceFS: ...

    def pull(self, device: DevicePath, local: str) -> None: ...

    def find(
        self,
        dir: str,
        ty: FindType,
        on_found: Callable[[str], object],
        *,
        limits: Optional[FindLimits] = ...,
        name: Optional[FindName] = ...,
    ) -> None: ...


class DevicePath:
    def __new__(cls, s: str) -> DevicePath: ...
    def __repr__(self) -> str: ...

    @staticmethod
    def from_squashed(s: str) -> DevicePath: ...

    @property
    def extension(self) -> Optional[str]: ...

    @property
    def device_file_name(self) -> str: ...

    @property
    def device_str(self) -> str: ...


class UnknownBool:
    @staticmethod
    def unknown() -> UnknownBool: ...
    @staticmethod
    def true() -> UnknownBool: ...
    @staticmethod
    def false() -> UnknownBool: ...

    @property
    def is_unknown(self) -> bool: ...
    @property
    def is_true(self) -> bool: ...
    @property
    def is_false(self) -> bool: ...

    def __repr__(self) -> str: ...

    TRUE: ClassVar[UnknownBool]
    FALSE: ClassVar[UnknownBool]
    UNKNOWN: ClassVar[UnknownBool]


class ClassName:
    def __new__(cls, name: str) -> ClassName: ...

    @staticmethod
    def from_split_manifest(pkg: str, name: str) -> ClassName: ...

    def has_pkg(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def get_simple_class_name(self) -> str: ...
    def pkg_as_java(self) -> str: ...
    def is_java(self) -> bool: ...
    def is_smali(self) -> bool: ...
    def get_java_name(self) -> str: ...
    def get_smali_name(self) -> str: ...


class ExitStatus:
    def ok(self) -> bool: ...
    def as_int(self) -> Optional[int]: ...


class CmdOutput:
    @property
    def status(self) -> ExitStatus: ...

    @property
    def stdout(self) -> bytes: ...

    @property
    def stderr(self) -> bytes: ...

    def throw_on_status(self) -> None: ...
    def ok(self) -> bool: ...


class AccessFlag:
    def __new__(cls, value: int = 0) -> AccessFlag: ...

    @staticmethod
    def from_bits(value: int) -> Optional[AccessFlag]: ...
    @staticmethod
    def from_bits_truncate(value: int) -> AccessFlag: ...

    def bits(self) -> int: ...
    def is_empty(self) -> bool: ...
    def contains(self, other: AccessFlag) -> bool: ...
    def intersects(self, other: AccessFlag) -> bool: ...

    def union(self, other: AccessFlag) -> AccessFlag: ...
    def intersection(self, other: AccessFlag) -> AccessFlag: ...
    def difference(self, other: AccessFlag) -> AccessFlag: ...
    def symmetric_difference(self, other: AccessFlag) -> AccessFlag: ...
    def without(self, other: AccessFlag) -> AccessFlag: ...

    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    def __or__(self, rhs: AccessFlag) -> AccessFlag: ...
    def __and__(self, rhs: AccessFlag) -> AccessFlag: ...
    def __xor__(self, rhs: AccessFlag) -> AccessFlag: ...

    UNSET: ClassVar[AccessFlag]
    PUBLIC: ClassVar[AccessFlag]
    PRIVATE: ClassVar[AccessFlag]
    PROTECTED: ClassVar[AccessFlag]
    STATIC: ClassVar[AccessFlag]
    FINAL: ClassVar[AccessFlag]
    SYNCHRONIZED: ClassVar[AccessFlag]
    BRIDGE: ClassVar[AccessFlag]
    VARARGS: ClassVar[AccessFlag]
    NATIVE: ClassVar[AccessFlag]
    ABSTRACT: ClassVar[AccessFlag]
    STRICTFP: ClassVar[AccessFlag]
    SYNTHETIC: ClassVar[AccessFlag]
    CONSTRUCTOR: ClassVar[AccessFlag]
    DECLARED_SYNCHRONIZED: ClassVar[AccessFlag]
    INTERFACE: ClassVar[AccessFlag]
    ENUM: ClassVar[AccessFlag]
    ANNOTATION: ClassVar[AccessFlag]
    VOLATILE: ClassVar[AccessFlag]
    TRANSIENT: ClassVar[AccessFlag]

    WHITELIST: ClassVar[AccessFlag]
    GREYLIST: ClassVar[AccessFlag]
    BLACKLIST: ClassVar[AccessFlag]
    GREYLIST_MAX_O: ClassVar[AccessFlag]
    GREYLIST_MAX_P: ClassVar[AccessFlag]
    GREYLIST_MAX_Q: ClassVar[AccessFlag]
    GREYLIST_MAX_R: ClassVar[AccessFlag]
    GREYLIST_MAX_S: ClassVar[AccessFlag]
    GREYLIST_MAX_T: ClassVar[AccessFlag]
    GREYLIST_MAX_U: ClassVar[AccessFlag]
    GREYLIST_MAX_V: ClassVar[AccessFlag]

    ANDROID_RESTRICTIONS: ClassVar[AccessFlag]

    CORE_PLATFORM_API: ClassVar[AccessFlag]
    TEST_API: ClassVar[AccessFlag]


class GraphDB:
    def __new__(cls, ctx: Optional[Context] = ...) -> GraphDB: ...

    def get_all_sources(self) -> set[str]: ...

    def find_child_classes_of(
        self,
        parent: str,
        *,
        parent_source: Optional[str] = ...,
        child_source: Optional[str] = ...,
    ) -> list[ClassSpec]: ...

    def find_classes_implementing(
        self,
        iface: str,
        *,
        iface_source: Optional[str] = ...,
        impl_source: Optional[str] = ...,
    ) -> list[ClassSpec]: ...

    def find_callers(
        self,
        *,
        class_: Optional[str] = ...,
        name: Optional[str] = ...,
        signature: Optional[str] = ...,
        method_source: Optional[str] = ...,
        call_source: Optional[str] = ...,
        depth: int = ...,
    ) -> list[MethodCallPath]: ...

    def find_outgoing_calls(
        self,
        *,
        class_: Optional[str] = ...,
        name: Optional[str] = ...,
        signature: Optional[str] = ...,
        source: Optional[str] = ...,
        depth: int = ...,
    ) -> list[MethodCallPath]: ...

    def get_classes_for(self, src: str) -> list[ClassName]: ...
    def get_methods_for(self, source: str) -> list[MethodSpec]: ...


class CachingGraphDB(GraphDB): ...


class ClassSpec:
    def is_public(self) -> bool: ...
    def is_not_abstract(self) -> bool: ...

    @property
    def name(self) -> ClassName: ...
    @property
    def source(self) -> str: ...
    @property
    def access_flags(self) -> AccessFlag: ...

    def __str__(self) -> str: ...


class MethodSpec:
    @property
    def class_(self) -> ClassName: ...
    @property
    def ret(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def signature(self) -> str: ...
    @property
    def source(self) -> str: ...

    def __str__(self) -> str: ...


class MethodCallPath:
    @property
    def path(self) -> list[MethodSpec]: ...

    def source(self) -> str: ...
    def initial(self) -> MethodSpec: ...


class DeviceDB:
    def __new__(cls, ctx: Optional[Context] = ...) -> DeviceDB: ...

    def get_all_system_service_impls(self) -> Mapping[str, list[SystemServiceImpl]]: ...
    def get_permission_by_id(self, sel: int) -> Permission: ...
    def get_permissions(self) -> list[Permission]: ...

    def get_provider_by_id(self, sel: int) -> Provider: ...
    def get_providers(self) -> list[Provider]: ...

    def get_service_by_id(self, sel: int) -> Service: ...
    def get_services(self) -> list[Service]: ...

    def get_receiver_by_id(self, sel: int) -> Receiver: ...
    def get_receivers(self) -> list[Receiver]: ...

    def get_activity_by_id(self, sel: int) -> Activity: ...
    def get_activities(self) -> list[Activity]: ...

    def get_system_service_by_id(self, sel: int) -> SystemService: ...
    def get_system_services(self) -> list[SystemService]: ...
    def get_system_services_name_like(self, sel: str) -> list[SystemService]: ...
    def get_system_service_by_name(self, sel: str) -> SystemService: ...
    def get_system_service_methods(self) -> list[SystemServiceMethod]: ...

    def get_device_property_by_id(self, sel: int) -> DeviceProperty: ...
    def get_device_properties(self) -> list[DeviceProperty]: ...
    def get_device_property_by_name(self, sel: str) -> DeviceProperty: ...
    def get_device_properties_like(self, sel: str) -> list[DeviceProperty]: ...

    def get_apk_by_id(self, sel: int) -> Apk: ...
    def get_apks(self) -> list[Apk]: ...
    def get_debuggable_apks(self) -> list[Apk]: ...
    def get_apk_by_app_name(self, sel: str) -> Apk: ...
    def get_apk_by_apk_name(self, sel: str) -> Apk: ...
    def get_apk_by_device_path(self, sel: str) -> Apk: ...

    def get_normal_permissions(self) -> list[Permission]: ...
    def get_permission_by_apk(self, sel: int) -> Permission: ...
    def get_permission_by_name(self, sel: str) -> Permission: ...
    def get_permissions_by_name_like(self, sel: str) -> list[Permission]: ...

    def get_system_service_impls(self, sel: int) -> list[SystemServiceImpl]: ...
    def get_system_service_methods_by_service_id(
        self, sel: int
    ) -> list[SystemServiceMethod]: ...

    def get_provider_containing_authority(self, sel: str) -> Provider: ...
    def get_receivers_by_apk_id(self, sel: int) -> list[Receiver]: ...
    def get_services_by_apk_id(self, sel: int) -> list[Service]: ...
    def get_activities_by_apk_id(self, sel: int) -> list[Activity]: ...
    def get_providers_by_apk_id(self, sel: int) -> list[Provider]: ...

    def get_diff_sources(self) -> list[DiffSource]: ...
    def get_diff_source_by_name(self, sel: str) -> DiffSource: ...

    def get_permission_diffs_by_diff_id(self, sel: int) -> list[DiffedPermission]: ...
    def get_permission_diffs_by_diff_name(self, sel: str) -> list[DiffedPermission]: ...

    def get_apk_diffs_by_diff_id(self, sel: int) -> list[DiffedApk]: ...
    def get_apk_diffs_by_diff_name(self, sel: str) -> list[DiffedApk]: ...

    def get_system_service_diffs_by_diff_id(
        self, sel: int
    ) -> list[DiffedSystemService]: ...
    def get_system_service_diffs_by_diff_name(
        self, sel: str
    ) -> list[DiffedSystemService]: ...

    def get_system_service_method_diffs_by_diff_id(
        self, sel: int
    ) -> list[DiffedSystemServiceMethod]: ...
    def get_system_service_method_diffs_by_diff_name(
        self, sel: str
    ) -> list[DiffedSystemServiceMethod]: ...
    def get_system_service_method_diffs_for_service(
        self, owner_id: int, diff_id: int
    ) -> list[DiffedSystemServiceMethod]: ...

    def get_service_diffs_by_diff_id(self, sel: int) -> list[DiffedService]: ...
    def get_service_diffs_by_diff_name(self, sel: str) -> list[DiffedService]: ...
    def get_service_diffs_for_apk(
        self, owner_id: int, diff_id: int
    ) -> list[DiffedService]: ...

    def get_provider_diffs_by_diff_id(self, sel: int) -> list[DiffedProvider]: ...
    def get_provider_diffs_by_diff_name(self, sel: str) -> list[DiffedProvider]: ...
    def get_provider_diffs_for_apk(
        self, owner_id: int, diff_id: int
    ) -> list[DiffedProvider]: ...

    def get_activity_diffs_by_diff_id(self, sel: int) -> list[DiffedActivity]: ...
    def get_activity_diffs_by_diff_name(self, sel: str) -> list[DiffedActivity]: ...
    def get_activity_diffs_for_apk(
        self, owner_id: int, diff_id: int
    ) -> list[DiffedActivity]: ...

    def get_receiver_diffs_by_diff_id(self, sel: int) -> list[DiffedReceiver]: ...
    def get_receiver_diffs_by_diff_name(self, sel: str) -> list[DiffedReceiver]: ...
    def get_receiver_diffs_for_apk(
        self, owner_id: int, diff_id: int
    ) -> list[DiffedReceiver]: ...

    def get_fuzz_result_by_id(self, sel: int) -> FuzzResult: ...
    def get_fuzz_results(self) -> list[FuzzResult]: ...
    def get_endpoints_by_security(self, sel: bool) -> list[FuzzResult]: ...


class DeviceProperty:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...


class Permission:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def protection_level(self) -> str: ...
    @property
    def source_apk_id(self) -> int: ...


class ApkPermission:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def apk_id(self) -> int: ...


class PermissionDiff:
    @property
    def id(self) -> int: ...
    @property
    def permission(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def protection_level_matches_diff(self) -> bool: ...
    @property
    def diff_protection_level(self) -> Optional[str]: ...


class DiffedPermission:
    def __str__(self) -> str: ...
    @property
    def permission(self) -> Permission: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def protection_level_matches_diff(self) -> bool: ...
    @property
    def diff_protection_level(self) -> Optional[str]: ...


class ProtectedBroadcast:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...


class UnprotectedBroadcast:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def diff_source(self) -> int: ...


class Apk:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def app_name(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def is_debuggable(self) -> bool: ...
    @property
    def is_priv(self) -> bool: ...
    @property
    def device_path(self) -> DevicePath: ...


class ApkWithPermissions:
    @property
    def apk(self) -> Apk: ...
    @property
    def permissions(self) -> list[str]: ...


class DiffedApk:
    def __str__(self) -> str: ...
    @property
    def apk(self) -> Apk: ...
    @property
    def exists_in_diff(self) -> bool: ...


class ApkDiff:
    @property
    def id(self) -> int: ...
    @property
    def apk(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...


class Receiver:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def class_name(self) -> ClassName: ...
    @property
    def exported(self) -> bool: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def pkg(self) -> str: ...
    @property
    def apk_id(self) -> int: ...
    @property
    def permission(self) -> Optional[str]: ...


class ReceiverDiff:
    @property
    def id(self) -> int: ...
    @property
    def receiver(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...


class DiffedReceiver:
    def __str__(self) -> str: ...
    @property
    def receiver(self) -> Receiver: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...


class Service:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def class_name(self) -> ClassName: ...
    @property
    def exported(self) -> bool: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def pkg(self) -> str: ...
    @property
    def apk_id(self) -> int: ...
    @property
    def returns_binder(self) -> UnknownBool: ...
    @property
    def permission(self) -> Optional[str]: ...


class ServiceDiff:
    @property
    def id(self) -> int: ...
    @property
    def service(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...


class DiffedService:
    def __str__(self) -> str: ...
    @property
    def service(self) -> Service: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...


class Activity:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def class_name(self) -> ClassName: ...
    @property
    def exported(self) -> bool: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def pkg(self) -> str: ...
    @property
    def apk_id(self) -> int: ...
    @property
    def permission(self) -> Optional[str]: ...


class ActivityDiff:
    @property
    def id(self) -> int: ...
    @property
    def activity(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...


class DiffedActivity:
    def __str__(self) -> str: ...
    @property
    def activity(self) -> Activity: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...


class Provider:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def authorities(self) -> str: ...
    @property
    def grant_uri_permissions(self) -> bool: ...
    @property
    def exported(self) -> bool: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def apk_id(self) -> int: ...
    @property
    def permission(self) -> Optional[str]: ...
    @property
    def read_permission(self) -> Optional[str]: ...
    @property
    def write_permission(self) -> Optional[str]: ...


class ProviderDiff:
    @property
    def id(self) -> int: ...
    @property
    def provider(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def write_permission_matches_diff(self) -> bool: ...
    @property
    def read_permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...
    @property
    def diff_write_permission(self) -> Optional[str]: ...
    @property
    def diff_read_permission(self) -> Optional[str]: ...


class DiffedProvider:
    def __str__(self) -> str: ...
    @property
    def provider(self) -> Provider: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def exported_matches_diff(self) -> bool: ...
    @property
    def permission_matches_diff(self) -> bool: ...
    @property
    def write_permission_matches_diff(self) -> bool: ...
    @property
    def read_permission_matches_diff(self) -> bool: ...
    @property
    def diff_permission(self) -> Optional[str]: ...
    @property
    def diff_write_permission(self) -> Optional[str]: ...
    @property
    def diff_read_permission(self) -> Optional[str]: ...


class SystemServiceImpl:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def system_service_id(self) -> int: ...
    @property
    def source(self) -> str: ...
    @property
    def class_name(self) -> ClassName: ...


class SystemServiceMethod:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def system_service_id(self) -> int: ...
    @property
    def transaction_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def signature(self) -> Optional[str]: ...
    @property
    def return_type(self) -> Optional[str]: ...
    @property
    def smalisa_hash(self) -> Optional[str]: ...


class SystemServiceMethodDiff:
    @property
    def id(self) -> int: ...
    @property
    def method(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def hash_matches_diff(self) -> UnknownBool: ...


class DiffedSystemServiceMethod:
    def __str__(self) -> str: ...
    @property
    def method(self) -> SystemServiceMethod: ...
    @property
    def exists_in_diff(self) -> bool: ...
    @property
    def hash_matches_diff(self) -> UnknownBool: ...


class SystemService:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def can_get_binder(self) -> UnknownBool: ...
    @property
    def iface(self) -> Optional[ClassName]: ...


class SystemServiceDiff:
    @property
    def id(self) -> int: ...
    @property
    def system_service(self) -> int: ...
    @property
    def diff_source(self) -> int: ...
    @property
    def exists_in_diff(self) -> bool: ...


class DiffedSystemService:
    def __str__(self) -> str: ...
    @property
    def service(self) -> SystemService: ...
    @property
    def exists_in_diff(self) -> bool: ...


class DiffSource:
    def __str__(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...


class FuzzResult:
    @property
    def id(self) -> int: ...
    @property
    def service_name(self) -> str: ...
    @property
    def method_name(self) -> str: ...
    @property
    def exception_thrown(self) -> bool: ...
    @property
    def security_exception_thrown(self) -> bool: ...


class ParcelValue:
    @staticmethod
    def Long(*, long: int) -> ParcelValue: ...
    @staticmethod
    def Int(*, int: int) -> ParcelValue: ...
    @staticmethod
    def Short(*, short: int) -> ParcelValue: ...
    @staticmethod
    def Byte(*, byte: int) -> ParcelValue: ...
    @staticmethod
    def Bool(*, bool: bool) -> ParcelValue: ...
    @staticmethod
    def Double(*, double: float) -> ParcelValue: ...
    @staticmethod
    def Float(*, float: float) -> ParcelValue: ...

    @staticmethod
    def Binder() -> ParcelValue: ...
    @staticmethod
    def Null() -> ParcelValue: ...

    @staticmethod
    def WriteFd(*, write_fd: str) -> ParcelValue: ...
    @staticmethod
    def ReadFd(*, read_fd: str) -> ParcelValue: ...

    @staticmethod
    def String(*, string: str) -> ParcelValue: ...

    @staticmethod
    def RawByteArray(*, raw_byte_array: bytes) -> ParcelValue: ...
    @staticmethod
    def HexByteArray(*, hex_byte_array: str) -> ParcelValue: ...

    @staticmethod
    def Bundle(*, bundle: Mapping[str, ParcelValue]) -> ParcelValue: ...
    @staticmethod
    def Map(*, map: Mapping[ParcelValue, ParcelValue]) -> ParcelValue: ...
    @staticmethod
    def List(*, list: Sequence[ParcelValue]) -> ParcelValue: ...
    @staticmethod
    def Complex(*, complex: Sequence[ParcelValue]) -> ParcelValue: ...


class AppServer:
    def __new__(cls, ctx: Optional[Context] = ...) -> AppServer: ...

    @staticmethod
    def connect(addr: str, port: int) -> AppServer: ...

    def sh(self, cmd: str, *, shell: Optional[str] = ...) -> CommandResult: ...

    def provider_call(
        self, uri: str, *, method: str, arg: Optional[str] = ...
    ) -> str: ...

    def provider_insert(
        self, uri: str, data: Mapping[str, ParcelValue]
    ) -> Optional[str]: ...

    def provider_query(
        self,
        uri: str,
        *,
        projection: Optional[list[str]] = ...,
        selection: Optional[str] = ...,
        selection_args: Optional[list[str]] = ...,
        query_args: Optional[list[ParcelValue]] = ...,
        sort_order: Optional[str] = ...,
    ) -> str: ...

    def provider_delete(
        self,
        uri: str,
        *,
        where_clause: Optional[str] = ...,
        selection_args: Optional[list[str]] = ...,
    ) -> int: ...

    def provider_read(self, uri: str) -> Optional[bytes]: ...
    def provider_write(self, uri: str, data: bytes) -> str: ...

    def system_service_shell_cmd(
        self,
        service: str,
        cmd: Optional[str],
        timeout: int,
    ) -> CommandResult: ...

    def call_system_service(
        self,
        name: str,
        txn: int,
        *,
        iface: Optional[str] = ...,
        parcel_data: Optional[list[ParcelValue]] = ...,
    ) -> str: ...

    def call_app_service(
        self,
        txn: int,
        package: str,
        class_: str,
        *,
        iface: Optional[str] = ...,
        action: Optional[str] = ...,
        parcel_data: Optional[list[ParcelValue]] = ...,
    ) -> str: ...

    def broadcast(
        self,
        action: Optional[str] = ...,
        data: Optional[str] = ...,
        package: Optional[str] = ...,
        class_: Optional[str] = ...,
        flags: Optional[list[str]] = ...,
        intent_data: Optional[Mapping[str, ParcelValue]] = ...,
    ) -> str: ...

    def start_service(
        self,
        action: Optional[str] = ...,
        data: Optional[str] = ...,
        package: Optional[str] = ...,
        class_: Optional[str] = ...,
        flags: Optional[list[str]] = ...,
        intent_data: Optional[Mapping[str, ParcelValue]] = ...,
    ) -> str: ...

    def start_activity(
        self,
        action: Optional[str] = ...,
        data: Optional[str] = ...,
        package: Optional[str] = ...,
        class_: Optional[str] = ...,
        flags: Optional[list[str]] = ...,
        intent_data: Optional[Mapping[str, ParcelValue]] = ...,
    ) -> str: ...


class CommandResult:
    @property
    def exit(self) -> int: ...
    @property
    def stdout(self) -> bytes: ...
    @property
    def stderr(self) -> bytes: ...

    def ok(self) -> bool: ...

    def stdout_string(self) -> str: ...
    def stderr_string(self) -> str: ...

    def __repr__(self) -> str: ...


class Adb:
    def __new__(cls, ctx: Optional[Context] = ...) -> Adb: ...

    def install(self, apk: str) -> None: ...
    def uninstall(self, apk: str) -> None: ...

    def pull(self, device: str, local: str) -> CmdOutput: ...
    def push(self, local: str, device: str) -> CmdOutput: ...

    def shell(self, shell_cmd: str) -> CmdOutput: ...

    def reverse_tcp_port(self, local_port: int, remote_port: int) -> CmdOutput: ...
    def forward_tcp_port(self, local_port: int, remote_port: int) -> CmdOutput: ...

    def forward_generic(self, local: str, remote: str) -> CmdOutput: ...
    def reverse_generic(self, local: str, remote: str) -> CmdOutput: ...
